spring:
  profiles:
    active:
    - dev
---

server:
  port: 8001

spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cloudDB01
  application:
    name: microservicecloud-dept



#通用mapper的配置
mapper:
  mappers: com.offcn.mapper
  identity: mysql
  not-empty: false

logging:
  level:
     com.offcn.mapper: debug

#将服务注册给注册中心
eureka:
  client:
    service-url:
      defaultZone : http://localhost:7001/eureka
  instance:
    instance-id: microservicecloud-dept:8001  #自定义服务名称信息
    prefer-ip-address: true   #访问路径可以显示ip地址

info:
  app.name: offcn-microservicecloud
  company.name: www.offcn.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001

spring:
  profiles: test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cloudDB01
  application:
    name: microservicecloud-dept



#通用mapper的配置
mapper:
  mappers: com.offcn.mapper
  identity: mysql
  not-empty: false

logging:
  level:
     com.offcn.mapper: debug

#将服务注册给注册中心
eureka:
  client:
    service-url:
      defaultZone : http://localhost:7001/eureka
  instance:
    instance-id: microservicecloud-dept:8001  #自定义服务名称信息
    prefer-ip-address: true   #访问路径可以显示ip地址

info:
  app.name: offcn-microservicecloud
  company.name: www.offcn.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$